---
title: "Visualizaciones iteractivas"
---

Este es el citio para las visualizaciones.

**Las visualizaciones son autom치ticas e iteractivas**
```{r echo=FALSE, include=FALSE}

library(dplyr)
library(ggvis)
library(quantmod)
library(lubridate)
library(ggplot2)
library(manipulate) 
library(dygraphs)
library(xts)
library(wbstats)
library(WDI)
library(gdata)
datos_clase2 <- wbcache(lang = "es")

BOLIVIA = WDI(indicator = c("NE.TRD.GNFS.ZS","BG.GSR.NFSV.GD.ZS","NV.AGR.TOTL.ZS","NV.IND.MANF.ZS","NY.GDP.MKTP.KD"),
              country = c("BO"),
              start = 1976, end = 2018 , extra = TRUE)

BOLIVIA <-rename.vars(BOLIVIA, c("NE.TRD.GNFS.ZS","BG.GSR.NFSV.GD.ZS","NV.AGR.TOTL.ZS","NV.IND.MANF.ZS","NY.GDP.MKTP.KD"),c("COMERCIO","SERVICIOS","AGRICULTURA","INDUSTRIALIZACION","PIB"))


C <- (((BOLIVIA$COMERCIO/100)*BOLIVIA$PIB)/1000000)
S <- (((BOLIVIA$SERVICIOS/100)*BOLIVIA$PIB)/1000000)
I <- (((BOLIVIA$INDUSTRIALIZACION/100)*BOLIVIA$PIB)/1000000)

x <-matrix(c(C,S,I), ncol = 3)
colnames(x)<-c("Comercio","Servicios","Industria")
t<- seq(as.Date('1976-01-01'),as.Date('2018-01-01'),by = "years")

Datos <-xts(x, order.by = t)

GRAPH1 <- cbind(Datos)
dygraph(GRAPH1) %>% 
  dyRangeSelector()

```
***el c칩digo puede ocultarse***
```{r echo=FALSE}

dygraph(GRAPH1, main ="Actividad Econ칩mica en Bolivia(millones de d칩lares)") %>% 
  dyOptions(stackedGraph = TRUE) %>%
  dyRangeSelector(height = 60)
```
